### ISSUE TITLE
Add replit link to showcase embeds 

### ISSUE THREAD

**Issue by BobobUnicorn** [TheCodingDen/projects-bot#292]
The original requirement was for public embeds; however, it might also be useful to do so for our private embeds as well for easier reviewing.

**Comment by nullishamy** [comment]
What exactly would this entail, and how would we integrate it? I'm assuming replit has an API we can use to clone repos into their service? How are we going to display this in the embeds, and will it be for both private & public or just the one?

This will also ideally wait until we are finished with #290 is complete so that the feature development is easier.

**Comment by BobobUnicorn** [comment]
We'd add a link to our embeds that allow someone to click a link to create a repl.it repl that clones the repo and presumably opens it. I'd imagined a new section that just says "Open in replit".

I think both embeds, just so we can have potentially easier reviewing.

API requires investigation.
